/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/activity/ActivityCard.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpCalendar: typeof import('~icons/ep/calendar')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpPictureRounded: typeof import('~icons/ep/picture-rounded')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    ProfilePortfolio: typeof import('./src/components/profile/ProfilePortfolio.vue')['default']
    ProfileRatings: typeof import('./src/components/profile/ProfileRatings.vue')['default']
    ProfileSidebar: typeof import('./src/components/profile/ProfileSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
