// <auto-generated />
using System;
using AperturePlus.RatingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AperturePlus.RatingService.Infrastructure.Migrations
{
    [DbContext(typeof(RatingServiceDbContext))]
    partial class RatingServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AperturePlus.RatingService.Domain.Entities.PendingRating", b =>
                {
                    b.Property<Guid>("PendingRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RateToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RatedUserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PendingRatingId");

                    b.ToTable("PendingRatings");
                });

            modelBuilder.Entity("AperturePlus.RatingService.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RateByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RateToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RatedUserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
